[[session]]
name = "Home"
path = "/home/d7om/"

[[session]]
name = "Downloads 󰉍"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "tmux config "
path = "/home/d7om"
startup_command = "nvim .tmux.conf"

[[session]]
name = "Nvim config "
path = "~/.config/nvim/"
startup_command = "v"

[[session]]
name = "Notes 󰎚"
path = "~/Notes/"
startup_command = "nvim +ObsidianQuickSwitch"

[[session]]
name = "LMS "
path = "~/Projects/Learning-management-system/"
startup_command = "~/.config/sesh/scripts/lms.sh"
