[[session]]
name = "Home"
path = "/home/d7om/"

[[session]]
name = "Tap 󰵷"
path = "~/Projects/Work/Tap/"
startup_command = "~/.config/sesh/scripts/tap.sh"

[[session]]
name = "Downloads 󰉍"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "Nvim config "
path = "~/.config/nvim/"
startup_command = "v"

[[session]]
name = "Homelab "
path = "~/HomeLab/"
startup_command = "ssh homelab"

[[session]]
name = "Notes 󰎚"
path = "~/Notes/"
startup_command = "nvim +ObsidianQuickSwitch"

# [[session]]
# name = "LMS "
# path = "~/Projects/Learning-management-system/"
# startup_command = "~/.config/sesh/scripts/lms.sh"
