"$schema" = 'https://starship.rs/config-schema.json'

format = """
 [](surface0)\
$os\
$username\
[](bg:peach fg:surface0)\
$directory\
[](fg:peach bg:green)\
$git_branch\
[](fg:green bg:blue)\
$docker_context\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$time\
[](fg:blue bg:purple)\
$cmd_duration\
[ ](fg:purple)\
$line_break$character"""


palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#CEB37C'
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
purple = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[cmd_duration]
min_time = 2000
format = "($style )[ $duration](bg:purple bold fg:black)"
style = "bg:purple bold fg:yellow"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰣇 "
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇 "
CachyOS = "󰣇 "
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = false
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:peach"
format = "[ $path ]($style)"
fish_style_pwd_dir_length = 2
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Projects" = "󰲋 "
"/media/Main/Linux/Projects/" = "󰲋 "
"/media/Main/Linux/Downloads/" = " "
"/media/Main/Linux/" = "~/D"

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:teal"
# format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'
modified = '*${count}'
ahead = "↑${count} "
behind = "↓${count} "
diverged = "↕${ahead_count} ${behind_count}"
untracked = "?${count} "
conflicted = "≠${count} "
staged = "✓${count} "
stashed = "󰸐${count} "
format = """\
[$ahead_behind](bold red bg:green)\
[$stashed](bold surface1 bg:green)\
[$behind_behind](bold red bg:green)\
[$diverged](bold yellow bg:green)\
[$conflicted](bold red bg:green)\
[$modified](bold color_purple bg:green)\
[$untracked](bold color_blue bg:green)\
[$staged](bold maroon bg:green)\
"""

[nodejs]
symbol = "󰎙"
style = "bg:blue"
# format = '[[ $symbol  ](fg:base bg:blue)]($style)'
format = '[[ $symbol ](fg:color_aqua bg:blue)]($style)'

[c]
symbol = " "
style = "bg:blue"
format = '[[ $symbol ](fg:base bg:blue)]($style)'

[rust]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ](fg:color_orange bg:blue)]($style)'

[golang]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ](fg:color_blue bg:blue)]($style)'

[php]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ](fg:base bg:blue)]($style)'

[java]
symbol = " "
style = "bg:blue"
format = '[[ $symbol ](fg:base bg:blue)]($style)'

[kotlin]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ](fg:base bg:blue)]($style)'

[haskell]
symbol = ""
style = "bg:blue"
format = '[[ $symbol ](fg:base bg:blue)]($style)'

[python]
symbol = ""
style = "bg:blue"
format = '[[ $symbol $virtualenv ](fg:yellow bg:blue)]($style)'

[docker_context]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol($context) ](fg:#83a598 bg:blue)]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:red bg:purple)]($style) '

[line_break]
disabled = false

[character]
disabled = false
success_symbol = ' [](bold fg:green)'
error_symbol = ' [](bold fg:red)'
vimcmd_symbol = ' [](bold fg:blue)'
vimcmd_replace_one_symbol = ' [](bold fg:red)'
vimcmd_replace_symbol = ' [](bold fg:red)'
vimcmd_visual_symbol = ' [](bold fg:lavender)'
